//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_dbfa.DBContext 
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_Employee
    {
        public int Id { get; set; }
        [Required(ErrorMessage ="Required")]
        public string Name { get; set; }
        [Required]
        [EmailAddress]
        public string Email { get; set; }       
        [Required]
        [MaxLength(10,ErrorMessage ="Mobile Number Should Be 10 digit")]
        public string Mobile { get; set; }
        [Required]
        public string Address { get; set; }
    }
}
